### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by Brainybrian316** [Brainybrian316/DEVise#68]
At a certain breakpoint the navigation bar gets discombobulated. look into issue to fix

**Comment by cobalt88** [comment]
at which break point?

**Comment by ethancahill** [comment]
statically it is working, however with dynamic renderings I haven't found a feasible solution yet. We will either have to create the navbar statically or find a different way to render each page. It will be a bit slower with a different method, however i am flexible on either. I'll leave it up to Vik on which path because it's his bar and just support whichever path
